$(document).ready ->

  submitUserData = (data) ->
    $.ajax
      url: '/routes/user.php'
      type: 'POST'
      data: data

  submitUserData({
      method: 'getActiveUser'
    }).then (res) ->
      res = JSON.parse res
      if res.status == 'success'
        submitUserData({
          method: 'getUserData'
          id: res.message
        }).then (userData) ->
          console.log userData


  $('#newUser').submit (e) ->
    e.preventDefault()
    submitUserData({
      method: 'new'
      username: $('form#newUser #username').val()
      password:  $('form#newUser #password').val()
    }).then (res) ->
      res = JSON.parse res
      if res.status == 'error'
        $('#newUser').find('.error').text res.message
      else
        location.reload()
    
  navToggle = ->
    navToggled = !navToggled
    $('nav#global').toggleClass 'navOn'
    $('.ionClose, .ionOpen').toggleClass 'buttonActive'

  navToggled = false

  $('#navToggle, .navContainer').click ->
    navToggle()

  toHash = (hash) ->
    $('body').animate({
      'scrollTop': $(hash).offset().top
    }, 750)
    return

  toLink= (link) ->

  $('a').click (e) ->
    e.preventDefault()
    href = $(this).attr 'href'
    if href.charAt(0) == '#'
      toHash href
    else
      $('#loader').show()
      $('#loader').css 'opacity', 1
      $('#loader').empty()
      $('#loader').animate({
        'left': '0px'
      }, 50, ->
        setTimeout ->
          window.location = href
        , 1000
      )

  load = ->
    $('#loader').css {
      'opacity': 0,
      'pointer-events': 'none',
    }
    if window.location.pathname.split("/").pop() != 'game.Shooting.html'
      $('body').css 'overflow-y', 'auto'
    setTimeout ->
      $('#loader').css {
        'display': 'none',
        'left': -1*$('#loader').width()
        }
    , 1000

  #loader delayed for testing

  imagesTotal = $('img').length
  segment = 100 / imagesTotal
  loaded = 0
  $(document).imagesLoaded().progress((instance, image) ->
    if image.isLoaded
      loaded += segment
      setTimeout ->
        $('#loader .loaderBar').css 'width', loaded + '%'
      , 100
    else
      $('.failed').append '<p>Fail to load: ' + image.img.src + '</p>'
    return
  ).done ->
    setTimeout ->
      load()
    , 500
    return

  $('.close, .closeForm').click ->
    $(this).parent().fadeOut()

  $('.show').click ->
    $($(this).attr('target')).fadeIn()

  $('button').click (e) ->
    e.preventDefault()

  return
# ---
# generated by js2coffee 2.2.0