$(document).ready ->

  navToggle = ->
    navToggled = !navToggled
    $('nav#global').toggleClass 'navOn'
    $('.ionClose, .ionOpen').toggleClass 'buttonActive'

  navToggled = false

  $('#navToggle, .navContainer').click ->
    navToggle()
  load = ->
    $('#loader').css 'opacity', 0
    $('body').css 'overflow-y', 'auto'
    setTimeout ->
      $('#loader').css 'display', 'none'
    , 1000

  #loader delayed for testing

  imagesTotal = $('img').length
  segment = 100 / imagesTotal
  loaded = 0
  $(document).imagesLoaded().progress((instance, image) ->
    animateText = (from, to) ->
    if image.isLoaded
      loaded += segment
      setTimeout ->
        $('#loader .loaderBar').css 'width', loaded + '%'
      , 1500
    else
      $('.failed').append '<p>Fail to load: ' + image.img.src + '</p>'
    return
  ).done ->
    setTimeout ->
      load()
    , 2000
    return

  return

# ---
# generated by js2coffee 2.2.0